import {FIREBASE_API,FIREBASE_AUTHDOMAIN,FIREBASE_PROJECTID,FIREBASE_STORAGEBUCKET,FIREBASE_MESSAGESSENDINGID,FIREBASE_APPID,API_URL} from '@env';

export default {
    FIREBASE_API,
    FIREBASE_AUTHDOMAIN,
    FIREBASE_PROJECTID,
    FIREBASE_STORAGEBUCKET,
    FIREBASE_MESSAGESSENDINGID,
    FIREBASE_APPID,
}